---
title: "Site selection for field work"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, error = FALSE, warning = FALSE)
```

# Steps to follow in this document:

1-  Will divide the NOVANA dataset in two datasets, the "Regularly sampled" and the "unfrequently sampled"
2- Within the "Regularly sampled", I will pick the top n samples in terms of directionality for biodiversity, so the top lets say the top 34 in gained diversity, top 34 in lost biodiversity, and top 34 in stability, so that is 103 sites.
3- The selected points in step 2 will be added to the Sampled dataset together with the Biowide, Microflora danica, and Agriculture sites (That is how I am calling the Moegens/ Mette sites)
4- Of all remaining sites either in the regularly sampled and unfrequently sampled figure out the top 1000 that are the furthest away environmentally (Ranked)
5- Hopefully after Monday's meeting with Christian, further use the abiotic variables in NOVANA,  to rerank the top 1000 using the abiotic dataset within the abiotic dataset

